# Generated by Django 3.0.4 on 2022-04-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appFactInv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encabezado_factura',
            name='estado_factura',
            field=models.BooleanField(default=True),
        ),
    ]
