# Generated by Django 3.0.4 on 2022-04-26 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appFactInv', '0002_auto_20220425_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='facturas_anuladas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=9)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appFactInv.productos')),
            ],
        ),
    ]
