# Generated by Django 3.0.4 on 2022-04-28 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appFactInv', '0003_facturas_anuladas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='facturas_anuladas',
        ),
    ]
